.gitignore, .husky/pre-commit, package-lock.json, package.json
- husky, lint-staged 설치 완료
- 커밋이 수행되기 전에, 각 폴더별로 설정된 eslint 파일에 의해 코드 수정 진행
Close #6
=> [Chore] Add pre-commit hook

client/package-lock.json, client/package.json
- React에서 환경 설정에 필요한 패키지 설치
- styled-components 설치
- react-router-dom 설치
- eslint, prettier 설치 
- eslint plugin, config 설치
- 안녕하세요
Close #11
=> [INIT] React Package 셋업

package-lock.json, package.json
- 프론트엔드 코드 lint_staged에서 faild 오류 문제
- 프론트엔드에서 사용하는 eslint 패키지를 루트에 설치했습니다.
- 백엔드쪽은 eslint 패키지를 제가 몰라서 따로 설치 안했습니다!
Close #20
=> [FIX] 프론트엔드 eslint 루트에 설치

client/README.md, client/src/App.tsx, client/src/pages/Exam.tsx, client/src/pages/ExamCreate.tsx, client/src/pages/FindId.tsx, client/src/pages/FindPw.tsx, client/src/pages/Home.tsx, client/src/pages/Login.tsx, client/src/pages/MyPage.tsx, client/src/pages/Problem.tsx, client/src/pages/ProblemCreate.tsx, client/src/pages/Review.tsx, client/src/pages/Search.tsx, client/src/pages/SignUp.tsx, client/src/router/Router.tsx
- 클라이언트 화면에 나타날 페이지 설정
- README.md에 URL 정의 
- react-router-dom을 사용해서 라우팅 세팅
Close #19
=> [INIT] React Router 셋업

client/src/styles/theme.ts
- 공통 스타일을 관리하기 위해서 Theme 생성
- styles/theme.ts 파일을 만들어서 공통 스타일을 관리
Close #25
=> [INIT] React style Theme Setup

client/src/assets/images/add.svg, client/src/components/common/Logo.tsx, client/src/components/dashboard/DashBoard.tsx, client/src/components/dashboard/DashBoardItem.tsx
- Logo 컴포넌트와 DashBoard 컴포넌트 작성
- Logo 컴포넌트의 경우 Link 태그를 사용해서 메인 화면으로 이동하는 기능이기 때문에 
특별한 작업은 하지 않고 추후 로고 확정 후 img 태그로 변경 필요
- DashBoard 컴포넌트의 경우 반응형을 고려해서 테블릿 사이즈부터는 한줄로 나오게 변경 
CSS 호버 애니메이션을 일단 넣어봄 
- 우선 배치, 디자인 틀만 잡았고 디자인 레이아웃에 대한 피드백 주시면 반영하겠습니다.
Close #24
=> [DESIGN] Common Component Logo & DashBoard

client/src/styles/theme.ts
- 프론트엔드 레이아웃 작업하면서 추가적으로 필요한 테마를 업데이트
- 모바일 반응형의 경우 width 100%를 하면 좌우 여백없이 꽉찬 화면이 되는데, 
그때 여백을 주고 싶은 경우 padding: 0 20px 로 통일하는 게 좋을 것 같다고 생각 
- font의 사이즈가 24가 최대인데 더 큰 28px이 하나 필요해서 추가
- color에서 gray 의 여러가지 색상 추가 Figma에도 업데이트 예정
- 필요에 의해서 Theme를 업데이트 했는데 피드백이 있다면 말씀해주세요!
=> [INIT] Update Theme

client/src/components/dashboard/DashBoard.tsx, client/src/components/header/Header.tsx, client/src/pages/Home.tsx
- Theme에 추가한 설정을 실제 프로젝트에 반영
- fontSize, fontWeight, color, padding 적용
- 제가 실수로 develop에 있는 테마가 오류가 나서 현재 pr을 merge하지 않으면 예외가 발생하더라구요
그래서 강제로 merge했습니다.
담부턴 확인하고 작업하겠읍니다....
=> [DESIGN] Theme Apply

client/src/components/header/Header.tsx, client/src/pages/Home.tsx, client/src/styles/theme.ts
- Width 값도 통일할 수 있다면 관리가 쉽다고 생각해서 추가했습니다.
- theme에 widths 추가
-> base ( PC ), responsive ( 반응형 )
=> [DESIGN] Update Theme

client/src/components/header/Header.tsx, client/src/components/header/Style.tsx, client/src/pages/home/Style.tsx
- 헤더의 디자인을 반응형에 맞춰서 수정
- 헤더 전체적인 디자인 수정
=> [DESIGN] Header 디자인 수정

server/package-lock.json, server/package.json, server/src/main.ts
- Swagger를 이용한 API Docs 작업 진행
- nestjs/swagger 패키지 설치
- 코드 작성이 있지는 않아요, swagger 추가를 통해 페이지만 생성이 되어 있고, 앞으로 작업할 컨트롤러의 경로마다 Decorator를 활용해서 설명을 추가할 수 있어요.
Close #60
=> [FEAT] Swagger 작업 진행

client/package-lock.json, client/package.json, client/src/index.tsx, client/src/react-query/queries/temp
- React Query 셋업
- react-query 패키지 설치
- 기본 폴더 세팅 및 토의
=> [INIT] React Query Setup

client/src/components/modal/Style.tsx, client/src/components/modal/create/Style.tsx, client/src/components/modal/create/index.tsx, client/src/components/modal/index.tsx, client/src/components/modal/search/Style.tsx, client/src/components/modal/search/index.tsx, client/src/hooks/useToggle.tsx, client/src/hooks/useToggleValue.tsx, client/src/pages/problemCreate/ProblemCreate.tsx, client/src/pages/problemCreate/Style.tsx, client/src/styles/Global.tsx, client/src/styles/theme.ts
- Problem Create 페이지에 있는 Create Modal ( 문제 생성 모달 ) 디자인
- Create Modal 디자인
- Global Style에 input 공용 설정 추가 
- 아직 레이아웃 작업을 우선으로 했고 리펙토링을 할 예정입니다. 
코드가 변경될 수 있읍니다. 
Close #80
=> [DESIGN] Problem Create Modal

server/package-lock.json, server/package.json, server/prisma/schema.prisma, server/src/AppModule.ts, server/src/decorators/UserDecorator.ts, server/src/modules/auth/AuthController.ts, server/src/modules/auth/strategies/JwtStrategy.ts, server/src/modules/question/QuestionController.ts, server/src/modules/question/QuestionModule.ts, server/src/modules/question/QuestionRepository.ts, server/src/modules/question/QuestionService.ts, server/src/modules/question/domain/Hashtag.ts, server/src/modules/question/domain/Option.ts, server/src/modules/question/domain/Question.ts, server/src/modules/question/domain/QuestionImage.ts, server/src/modules/question/dto/request/CreateQuestionRequest.ts, server/src/modules/question/dto/response/CreateQuestionResponse.ts, server/src/modules/question/enum/QuestionType.ts, server/src/modules/user/enum/OauthType.ts
- 문제 생성 API 구현
- 서비스 메소드 구현
- CreateQuestionRequest, CreateQuestionResponse DTO 작성
- 컨트롤러 메소드 구현
- 오프라인으로 만나서 인프라 구축하고 Object storage가 마련되면 유저 아바타와 함께 문제 image 부분도 추가할 계획입니다.
=> [FEAT] 문제 생성 API 구현

client/src/components/modal/Style.tsx, client/src/components/modal/create/Style.tsx, client/src/components/modal/search/Style.tsx, client/src/components/modal/search/index.tsx, client/src/pages/problemCreate/ProblemCreate.tsx
- 문제 검색 모달 디자인 완료
- 문제 검색 모달 디자인 완료
- 해당 부분 작업하면서 앞서 문제 생성 페이지 리팩토링 이야기를 했는데,
해당 리팩토링을 기준으로 검색 모달도 merge가 되면 추후 적용할 계획입니다. 
close #86
=> [DESIGN] Search Problem 모달

client/src/router/Router.tsx
- git이 폴더명 대소문자구분 불가한 부분에 대한 에러 해결
- src/pages/findId => FindId로 폴더명 변경
-
=> [HOTFIX] 폴더이름관련 에러 해결

.github/workflows/frontend.yml
- .github/workflows/frontend.yml 수정
- 경로수정
-
=> [FIX] frontend 배포환경 수정

.github/workflows/frontend.yml
- action 변경
- checkout action => appleboy/ssh-action으로 변경
-
=> [FIX] frontend cicd action 변경

client/src/App.test.tsx, client/src/pages/signup/SignUp.test.tsx, client/src/pages/signup/SignUp.tsx, client/src/pages/signup/constants.ts
- react-testing-library를 이용하여 테스트코드 작성
- signup.test.ts 작성
- 상수는 따로 constants.ts 파일 생성 후 분리 
- app.test.tsx는 cra 기본파일로서 app.tsx 테스트 파일이므로 삭제
-
=> [TEST] 회원가입 페이지에 대한 test 코드 작성

.github/workflows/front_dev.yml, .github/workflows/front_prod.yml, .github/workflows/frontend.yml
- github action 설정
- pm2 설정
- 서버 무중단 실행
- yml 설정
-
=> [FIX] frontend github action 개발 환경 우선 설정

.github/workflows/front_dev.yml
:
- 해당 오류 해결 테스트 pr
- action의 script를 secret으로 변경
-
=> [FIX] github action script를 secret으로 변경

client/package-lock.json, client/package.json, client/src/components/header/Style.tsx, client/src/components/modal/create/constants.ts, client/src/components/modal/create/index.tsx, client/src/pages/MyPage.tsx, client/src/pages/home/Style.tsx, client/src/pages/mypage/MyPage.tsx, client/src/pages/mypage/Style.tsx, client/src/pages/mypage/constants.ts, client/src/pages/workBookCreate/Style.tsx, client/src/router/Router.tsx, client/src/styles/theme.ts
- 마이페이지 레이아웃
- 마이페이지 레이아웃
- theme 부분에서 widths의 base의 방식을 좀 더 반응형을 매끄럽게 작업하려고 바로 width와 미디어쿼리를 사용했는데, 
명칭이 widths가 맞는지 모르겠네요...
- 마이페이지 속 내부 페이지 작업 시 ContentsContainer 의 height 이나, 배경을 필요에 따라 삭제해주시면 됩니다. 
Close #130
=> [DESIGN] Mypage Payout

client/src/components/chart/Style.tsx, client/src/components/header/Style.tsx
- 메인화면 특정 모바일 기기에서 반응형이 깨지는 부분을 확인해서 수정
- 메인화면 특정 모바일 기기에서 반응형이 깨지는 부분을 확인해서 수정
Close #132
=> [REFACTOR] 반응형 수정

client/src/App.tsx, client/src/components/modal/create/index.tsx, client/src/components/modal/search/index.tsx, client/src/index.tsx, client/src/mocks/handlers/question.ts, client/src/react-query/queryClient.ts, client/src/router/Router.tsx
- 굳이 에러처리가 필요없는 react query는 일괄적으로 처리할 수 있게 수정
- index.ts에 있던 React Query 설정 App.ts로 이동 
( Toast 설정을 위해서 )
- App.ts에서 전체적으로 전역 스타일, Toast 등을 설정할 수 있도록 적용
- toast는 아마? React에서 가장 많이 사용되는 걸로 알고있는 react-toastify 사용했습니다. 
더 좋은 패키지 혹은 다른 아이디어 환영
Close #140
=> [REFACTOR] React-Query Error

client/src/components/chart/Chart.tsx
- useArrayValue 미사용
- useArrayValue 로직 실제 사용되는 부분에서 제외
- 패기롭게 처음 프로젝트를 시작할 때 커스텀 훅을 남발했는데, 개발 시작 3주 차가 끝나가도록 사용을 안 하게 되어서
useArrayValue 친구는 저희와 함께 가지 못하게 되었습니다.... JOY를 표합니다. R.I.P
=> [REFACTOR] useArrayValue

client/src/components/common/Loading.tsx, client/src/components/modal/create/constants.ts, client/src/components/modal/create/index.tsx, client/src/components/modal/search/index.tsx, client/src/hooks/useArrayText.tsx, client/src/mocks/handlers/question.ts, client/src/mocks/handlers/workbook.ts, client/src/pages/workBookCreate/WorkBookCreate.tsx
- 문제 생성 페이지 리팩토링
- 검증 오류 명확화 
-> 오류 시 toast.error를 사용해서 오류 로그 출력
-> 문제 생성 시 hashtag 검증 제외, 문제 수 검증 추가, 문제 보기 중복 검증 추가
- loading 컴포넌트 생성 
-> 로딩 창이 필요한 경우 컴포넌트 호출 시 간단한 로딩화면 출력 
-> 부모 컴포넌트의 width, height를 가짐
=> [REFACTOR] workbook create

client/src/components/mypage/Workbook.tsx, client/src/components/workbookItem/Style.tsx, client/src/components/workbookItem/WorkbookItem.tsx, client/src/pages/Search.tsx, client/src/pages/mypage/MyPage.tsx, client/src/pages/mypage/Style.tsx, client/src/types/search.ts
- mypage에 나의 문제집, 공유 받은 문제집 컴포넌트 추가하기
- 두 컴포넌트 작성
- 기존에 만들었던 search workbook 결과 컴포넌트 재활용
-
=> [DESIGN] MyPage 의 나의 문제집 및 공유받은 문제집 컴포넌트 추가

server/prisma/schema.prisma, server/src/modules/test/TestRepository.ts, server/src/modules/test/TestService.ts, server/src/modules/test/domain/Test.ts, server/src/modules/test/dto/request/CreateTestRequest.ts, server/src/modules/test/dto/response/TestSimpleResponse.ts
- Test에 title 추가
- Test table 에 title column 추가로 인한 prisma schema 변경
- Test 도메인 클래스에 title field 추가
- test 생성 로직에 적용
-
=> [FEAT] Test에 title 추가

client/src/components/modal/create/index.tsx, client/src/components/modal/search/index.tsx, client/src/hooks/useInput.tsx, client/src/pages/signup/SignUp.tsx, client/src/pages/workbookCreate/index.tsx, client/src/router/Router.tsx
- ⚠️ 사소함 주의
- return value의 타입을 리스트에서 객체로 변환하였습니다
-
=> [REFECTOR] useInput return value 수정

client/src/pages/signup/SignUp.tsx, client/src/utils/constants.ts
=> [FEAT] 회원가입 api 연동

server/.env.example, server/package-lock.json, server/package.json, server/src/modules/common/CommonModule.ts, server/src/modules/common/ImageUploader.ts
- used aws-sdk to upload images to NCP Object storage
- multer, aws-sdk를 활용하여 이미지 업로더 작성
- 실행을 위해 BUCKET_URL, NCP_ACCESS_KEY, NCP_SECRET_ACCESS_KEY 를 .env에 추가해야 합니다. 말씀해주시면 키를 공유드리도록 하겠습니다.
=> [FEAT] 이미지 업로더 작성

server/src/modules/auth/AuthService.ts, server/src/modules/question/QuestionRepository.ts, server/src/modules/question/QuestionService.ts, server/src/modules/test/TestRepository.ts, server/src/modules/test/TestService.ts, server/src/modules/user/UserRepository.ts, server/src/modules/user/UserService.ts, server/src/modules/workbook/WorkbookRepository.ts, server/src/modules/workbook/WorkbookService.ts
- 피어세션때 고지한 대로 Transaction을 도입해 봤습니다.
- 슈루룩
- transaction api 내에 있는 애들은 test 시 mocking이 안된다는데, 추후에 제약이 생길까봐 걱정이 조금 되네요.
=> [REFACTOR] Transaction 도입

server/src/modules/common/MailService.ts
- 프론트엔드 경로 설정에 따른 코드 수정
- 사소한 경로 수정 및 텍스트 수정이 있었습니다.
- No Review Required
=> [FEAT] email template URI 변경

client/src/components/modal/createQuestion/index.tsx
- 충돌 발생 했을 때, 충돌 잡은 부분과 작업 분이 섞여서 올라갔네요;; 
고메나사이합니다;;
=> [FIX] CreateQuestion

client/src/api/auth.ts, client/src/api/index.ts, client/src/api/login.ts, client/src/api/question.ts, client/src/api/search.ts, client/src/api/test.ts, client/src/api/workbook.ts
- axios withCredentials default 세팅
- axios 를 index.ts에서 가져와서 customAxios에서 withCredentials를 true로 만들어서 
각 API에서 설정할 필요없게 수정
=> [REFACTER] Axios

server/src/AppModule.ts
- 모듈 import 관련 오류 수정
- 모듈 import 관련 오류 수정
- 리뷰 X
=> [FIX] 유저 모듈 미등록 상황 수정

client/src/api/workbook.ts, client/src/components/search/SearchResultItem/index.tsx, client/src/pages/workbookDetail/index.tsx
- 문제집 저장 API 연동
- 문제집 상세 페이지에서 문제집 저장 API 연동
- 문제집 검색 결과 페이지에서 문제집 저장 API 연동
- @caseBread 문제집 검색 결과와 상세 페이지에 우선 연동을 했는데, 따로 생각했던 방식이 있었다면 피드백 부탁드립니다. 
onClick에 걸어서 문제는 없을 것 같은데, 제가 만든 컴포넌트가 아니라 조심스럽네요
=> [FEAT] Workbook save

.github/workflows/frontend-dev.yml
- CI/CD 수정
- 디렉토리 잘못 입력한 부분 수정
- 죄송합니다.. 도게자 박겠습니다. 2
=> [FIX] CI/CD 파이프라인 동작하지 않는 오류 수정

client/src/components/solve/contents/index.tsx
- 충돌 난 코드가 그냥 merge가 된 것 같아서 fix 했습니다
- SERVICE_ROUTE 경로 변경
=> fix:confict

client/README.md, client/src/pages/mypage/index.tsx
=> [HOTFIX] 나의 시험지 생성 관련 리다이렉트 오류 수정

server/src/modules/question/dto/response/CreateQuestionResponse.ts
- 문제 생성 응답 수정
- add hashtags on response
- 해시태그가 없는 문제일 경우, 빈 배열로 데이터가 전달됩니다.
-
=> [FIX] 문제 생성 시 응답 객체 수정

server/src/modules/question/dto/response/GetQuestionsResponse.ts, server/src/modules/test/TestService.ts, server/src/modules/test/dto/request/CreateTestRequest.ts, server/src/modules/workbook/WorkbookController.ts, server/src/modules/workbook/WorkbookService.ts, server/src/modules/workbook/dto/request/SolveWorkbookQuestionRequest.ts
- 재완님 요청사항 수정
- 시험 생성 시 분, 초 입력 적용
- GetQuestionResponse 미사용 필드 주석 처리
- 문제집 문제 풀이 API 버그 수정
- 내 문제집 조회 / 검색 API 응답에 questions 추가
-
=> [FIX] 재완님 요청사항 수정

server/src/modules/common/PageRequest.ts, server/src/modules/testPaper/TestPaperController.ts, server/src/modules/testPaper/domain/TestPaperQuestion.ts, server/src/modules/testPaper/dto/request/GradeTestPaperQuestionRequest.ts, server/src/modules/testPaper/dto/request/MarkTestPaperQuestionRequest.ts
=> [HOTFIX] 채점 api 버그 수정

server/src/modules/common/ImageUploader.ts, server/src/modules/user/UserController.ts
- 유저 프로필 이미지 업로드 수정
- 추가적인 오류 발생 요소 수정
- Guard 가 사용되지 않던 오류 수정 (req.user 를 가져오지 못해 오류 발생)
- DB에 저장되는 URI 에 버킷이 빠져있어 이미지가 나오지 않던 오류 수정
- Gomennasai.. DOGEZA
=> [FIX] 유저 프로필 이미지 업로드 오류 수정

client/src/components/mypage/workbook/index.tsx, client/src/components/search/SearchResultItem/index.tsx
- 
- 문제집 상세보기 페이지 리다이렉트 주소 수정
-
=> [FIX] 리다이렉트 주소 수정

client/src/components/modal/searchWorkbook/index.tsx, client/src/components/solve/header/index.tsx, client/src/index.tsx, client/src/pages/testCreate/index.tsx, client/src/pages/workbook/index.tsx, client/src/types/question.ts, client/src/types/workbook.ts
=> [REFACTOR] 문제집 풀이 - API 연동

server/src/modules/question/QuestionController.ts, server/src/modules/user/UserController.ts, server/src/modules/user/UserRepository.ts, server/src/modules/user/UserService.ts, server/src/modules/user/dto/response/MyDataResponse.ts
- 메인페이지 필요 API 작업
- 프론트 화면에 맞는 정보 조회
- 현재 작성한 코드가 굉장히 마음에 들지 않아서 변경 예정에 있습니다. (기존 DTO 들 활용해서 동작하게 적느라 도메인 뒤섞이고 엉망이 되어 버림) 감안하고 코드 봐주세요.
=> [FEAT] 메인페이지 API 작업

client/src/components/modal/searchQuestion/index.tsx, client/src/components/solve/contents/Style.tsx, client/src/components/solve/contents/index.tsx, client/src/types/question.ts
- 문제집 생성 시 문제 검색 로직 처리
- 문제 생성 시 문제 검색 시 해쉬태그 출력
=> [REFACTOR] Search question

client/src/components/modal/createQuestion/forms/QuestionAnswerForm.tsx, client/src/components/modal/createQuestion/forms/QuestionInfoForm.tsx, client/src/components/search/TestSearchResultItem/index/index.tsx, client/src/components/solve/contents/index.tsx
- 문제 풀이 시 링크 변경 및 시험 링크 변경
- 어제 영상 촬영 시 필요한 디자인 수정 부분
- 링크 변경
- 디자인 수정
=> [REFACTOR] Workbook link

client/.env.development, client/.env.production, client/src/api/auth.ts, client/src/components/login/LoginModal.tsx, client/src/pages/findPw/FindPw.tsx, client/src/pages/login/Style.tsx, client/src/pages/login/constants.ts, client/src/pages/login/index.tsx, client/src/pages/signup/Style.tsx, client/src/pages/signup/index.tsx
- input 사이즈 안맞는 부분 수정 & 로고 크기 수정
- input 길이 변경
- 로고 크기 변경
=> [REFACTOR] 로그인 - 디자인

client/src/components/modal/createQuestion/index.tsx, client/src/components/modal/searchQuestion/Style.tsx, client/src/components/modal/searchQuestion/index.tsx, client/src/components/modal/searchWorkbook/Style.tsx, client/src/components/modal/searchWorkbook/index.tsx, client/src/pages/workbookCreate/Style.tsx, client/src/pages/workbookCreate/index.tsx, client/src/styles/questionList.tsx
- Question Naming
- Problem으로 작성된 컴포넌트, 함수, 변수 명 등을 백엔드 API와 통일을 위해  Question으로 변경
=> [REFACTOR] Question naming

client/.env.development, client/.env.production
=> [FIX] remove env

client/src/pages/login/index.tsx
=> [FIX] Login

client/src/api/workbook.ts, client/src/components/modal/searchQuestion/index.tsx, client/src/pages/workbookCreate/index.tsx
- Question 디자인 수정 
- Question 디자인 수정
=> [REFACTOR] Question_add

client/src/components/mypage/review/index.tsx
=> [FIX] 오답노트 수정 

client/src/components/mypage/workbook/index.tsx, client/src/types/search.ts
=> [HOTFIX] 나의 문제집 문제 수가 undefined로 출력되던 버그 수정
